### ISSUE TITLE
spatialite installation is broken on xenial, breaking the build

### ISSUE THREAD

**Issue by simonw** [simonw/cryptozoology#16]
First break was this one: https://travis-ci.com/simonw/cryptozoology/jobs/215652073

It looks like this was the first time the build ran against Ubuntu xenial - the previous succeeding build ran against Ubuntu trusty.

**Comment by simonw** [comment]
Now I'm getting this error:
```
Traceback (most recent call last):

  File "build_cryptids_database.py", line 124, in <module>

    build_database()

  File "build_cryptids_database.py", line 54, in build_database

    conn.load_extension(extension)

sqlite3.OperationalError: /usr/lib/x86_64-linux-gnu/libspatialite.so.7: undefined symbol: sqlite3_spatialite_init

The command "python build_cryptids_database.py" exited with 1.
```
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=910240 has some clues.

**Comment by simonw** [comment]
https://docs.travis-ci.com/user/trusty-to-xenial-migration-guide says Travis upgraded the default to xenial on August 13th 2019

**Comment by simonw** [comment]
That fixed it.
